FROM docker.elastic.co/elasticsearch/elasticsearch:8.13.4

# Si necesitas copiar algún archivo de configuración personalizado:
# COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Elasticsearch ya corre como usuario `elasticsearch`
# puedes cambiar configuraciones si es necesario
