FROM mongo:6

# Puedes agregar comandos aquí si necesitas extensiones, configuraciones o scripts personalizados

# Copiar archivos de configuración si es necesario
# COPY mongod.conf /etc/mongod.conf

# Exponer el puerto (aunque docker-compose ya lo maneja)
EXPOSE 27017
